// <auto-generated />
using System;
using FormulaUnoObligatorio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormulaUnoObligatorio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241115231256_CrearTablaEscuderia")]
    partial class CrearTablaEscuderia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormulaUnoObligatorio.Models.Carrera", b =>
                {
                    b.Property<int>("IdCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrera"));

                    b.Property<string>("CiudadCarrera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaCarrera")
                        .HasColumnType("date");

                    b.Property<string>("NombreCarrera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCarrera");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("FormulaUnoObligatorio.Models.Escuderia", b =>
                {
                    b.Property<int>("IdEscuderia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEscuderia"));

                    b.Property<string>("NombreEscuderia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisEscuderia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SponsorOficial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEscuderia");

                    b.ToTable("Escuderias");
                });

            modelBuilder.Entity("FormulaUnoObligatorio.Models.Piloto", b =>
                {
                    b.Property<int>("IdPiloto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPiloto"));

                    b.Property<string>("ApellidoPiloto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EscuderiaPilotoIdEscuderia")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int>("IdEscuderia")
                        .HasColumnType("int");

                    b.Property<string>("NombrePiloto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisPiloto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPiloto");

                    b.HasIndex("EscuderiaPilotoIdEscuderia");

                    b.ToTable("Pilotos");
                });

            modelBuilder.Entity("FormulaUnoObligatorio.Models.Piloto", b =>
                {
                    b.HasOne("FormulaUnoObligatorio.Models.Escuderia", "EscuderiaPiloto")
                        .WithMany("Pilotos")
                        .HasForeignKey("EscuderiaPilotoIdEscuderia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EscuderiaPiloto");
                });

            modelBuilder.Entity("FormulaUnoObligatorio.Models.Escuderia", b =>
                {
                    b.Navigation("Pilotos");
                });
#pragma warning restore 612, 618
        }
    }
}
